// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1pYcbnHbXpW5uNuDLQzWzutzH5R4rdJ0',
    appId: '1:722603646978:web:76300c6e034e24e6a5871b',
    messagingSenderId: '722603646978',
    projectId: 'workforce-47344',
    authDomain: 'workforce-47344.firebaseapp.com',
    storageBucket: 'workforce-47344.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt80VBroW95n7Id-cwT7egG6yGPD0oYvM',
    appId: '1:722603646978:android:da6af7badeb9ca6ba5871b',
    messagingSenderId: '722603646978',
    projectId: 'workforce-47344',
    storageBucket: 'workforce-47344.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnsifFcD-5YmAzxZLMb4ERrFT1fkDT_7s',
    appId: '1:722603646978:ios:edfff6bf3750f86ea5871b',
    messagingSenderId: '722603646978',
    projectId: 'workforce-47344',
    storageBucket: 'workforce-47344.firebasestorage.app',
    iosBundleId: 'com.example.workforce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnsifFcD-5YmAzxZLMb4ERrFT1fkDT_7s',
    appId: '1:722603646978:ios:edfff6bf3750f86ea5871b',
    messagingSenderId: '722603646978',
    projectId: 'workforce-47344',
    storageBucket: 'workforce-47344.firebasestorage.app',
    iosBundleId: 'com.example.workforce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1pYcbnHbXpW5uNuDLQzWzutzH5R4rdJ0',
    appId: '1:722603646978:web:1252cced56d1b635a5871b',
    messagingSenderId: '722603646978',
    projectId: 'workforce-47344',
    authDomain: 'workforce-47344.firebaseapp.com',
    storageBucket: 'workforce-47344.firebasestorage.app',
  );
}
